Accuracy Tests for Metafounders
XingerTang/AlphaPeel pull request #3
Opened 2024-05-17 15:26 UTC by RosCraddock

Completion of inputs and outputs for the accuracy tests described below:

- [ ] a test with single metafounder and user-provided alternative allele frequency
- [ ] a test with multiple metafounder in segregated lineages and user-provided alternative allele frequency
- [ ] a test with multiple metafounder with overlapping lineages and user-provided alternative allele frequency
- [ ] a test with multiple metafounder in segregated lineages and estimated alternative allele frequency
- [ ] a test with multiple metafounder iwith overlapping lineages and estimated alternative allele frequency

More refinements are needed, and the code needs to be tidied. More specifically, I am exploring alternatives for multiple metafounders with overlapping lineages (Test #2 in code) that provide more distinct allele frequencies.

Please check through when you have time. Let me know if you have any comments/suggestions!

2024-05-31 12:41 UTC, XingerTang requested changes
Sorry for letting you wait for so long. Your code is really well-written, thank you! I just added a few comments, please have a look at these whenever you get a chance. Additionally, I would like to see all the output files of these new simulations, please also push these files.

2024-05-31 12:41 UTC, XingerTang commented on tests/accuracy_tests/sim_for_alphapeel_accu_test/sim_for_accu.R
> +  tmp <- test[test == TRUE]
It might be better if we rename the variables``MF_A`` and ``MF_B`` as ``MF_A_alt_allele_prob`` and ``MF_B_alt_allele_prob``.

2024-05-31 12:41 UTC, XingerTang commented on tests/accuracy_tests/sim_for_alphapeel_accu_test/sim_for_accu.R
> +# REVIEW: AF still quite similar, explore alternative (crossing two separate pedigrees)
I'm wondering if we can separate the base pop with the alternative allele frequencies for each individual.

2024-05-31 12:41 UTC, XingerTang commented on tests/accuracy_tests/sim_for_alphapeel_accu_test/sim_for_accu.R
> +            row.names = FALSE, col.names = FALSE, quote = FALSE)
I just noticed that we haven't updated our documentation for the estimated alternative allele frequency outputs. Maybe we should open an issue for this.

2024-06-05 23:29 UTC, RosCraddock commented
Thank you for this Evie! I have addressed your comments above and will push this through now.

2024-06-06 08:37 UTC, merged

2024-06-06 08:39 UTC, XingerTang commented
Thanks! It is perfect! I've merged the commits and I will close the pull request.